### ISSUE TITLE
Post networking additions

### ISSUE THREAD

**Issue by Tacitor** [Tacitor/ICS4U-Settlers-Of-Catan#101]
- [x]  Issue #73 add a mouse motion listener
    - Button feedback when mousing over
    - Tool tips
- [x] Add animations from #134
- [ ] Add more sounds
    - Soud effecs
       - Dice rolling
       - building a new settlement
   - Music (potential ideas)
       - Ambient
       - Victory Music
- [x] Rework Instructions
    - For ease of use
    - Bigger Font Size
        - Create Margins 
- [x] Client settings menu separate from new game settings
- [x] Limited game pieces
    - Default option (15 road)
    - Custom option (infinite road, 20 road, etc.)
- [x] Change over all buttons to Settler Buttons
- [x] Add custom component focusing (tabbing around the buttons)
- [x] Change over all menus to custom frames and panels with settler buttons 
- [x] Add player-to-player trading
- [x] Make the "end current player's turn" button more intuitive as to who's turn is being ended
- [x] dev card tool tips
- [x] automatically switch to the development card view after the user buys one. #143
