### ISSUE TITLE
Native Neatened Networking TODO

### ISSUE THREAD

**Issue by Tacitor** [Tacitor/ICS4U-Settlers-Of-Catan#160]
**Native Neatened Networking TODO:**
- [x] Add back colour selection
- [x] Main lobby aggregation server
- [x] Labels on the join lobby panel that hints to needing a NEW game to join an empty lobby. Another hint that an empty is needed when making a new game
- [x] Add back Loading to online mode
- [x] Go through and delete old classes not needed anymore
- [ ] Add splash texts on main menu
- [x] Make the colour select buttons bigger
- [x] Go to main menu after game ending (win or exit)
- [x] Add colour dots to colour select panel

**Comment by Tacitor** [comment]
Splash texts

- Now with 10% less asbestos
- Recommended by 1 out of 10 dentists
- Ceterum censeo Carthaginem esse delendam
- Pet your car at least twice a day
- Car keys are best enjoyed with high dose ethanol
- Also try Minceraft
- Don't tell Klaus Teuber
- Open Source!
- Bet you couldn't do 5 times a 1000
- Almost as delicious as anthracite

**Comment by Tacitor** [comment]
No splash screens
